### ISSUE TITLE
成功编译后无法正常launch

### ISSUE THREAD

**Issue by 123295** [PolarisXQ/Fast-LIO2-Localization#3]
感谢作者的开源工作！
我是在arm结构orin nx的ubuntu20.04 ros2 foxy中运行的， mid360直接连接到orin nx上。
目前已经成功编译通过了，但是程序一直运行不起来，具体如下：

![Image](https://github.com/user-attachments/assets/96d98464-2a13-4bf6-9f22-28fa77a6a1e3)

请问你有遇到过这样的情况吗？我应该如何解决呢？

**Comment by 123295** [comment]
现在还没到重定位，只是想先建图。麻烦作者有空的时候解答一下，谢谢谢谢！

**Comment by PolarisXQ** [comment]
想问一下你按照实际情况更改过FAST_LIO/config/mid360.yaml了嘛？
```yaml
lid_topic:  "/livox/lidar"
imu_topic:  "/imu/data"

extrinsic_T:
extrinsic_R:
````

都要按照实际情况更改一下
